#+title: Loke - Curve Library
#+author: Ranjeeth Mahankali
#+filetags: :project:loke:

* NEXT tgahg8 - Support Elliptic Arcs
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 16:40
  :END:
  :LOGBOOK:
  - State "NEXT"       from "TODO"       [2026-06-06 Sat 16:48]
  :END:

  They can be represented as a SLERP of vectors of unequal lengths. Very similar
  to how arcs work, and just need the =TrigonometryAdaptor=. This will unlock
  the ability to projects arcs onto arbitrary planes.

  Still unclear whether to extend arcs to support both arcs and ellipses, or
  make a new curve type.

  <2026-06-06 Sat 19:31> Verified on Geogebra that the SLERP interpolation on
  vectors of arbitrary lengths nicely produces ellipses, that start and end
  exactly at the vectors being interpolated, as you change the parameter from 0
  to 1.

  <2026-06-12 Fri 10:11> Addeed simple functions to create elliptic arcs and
  tests for them. Now starting to expand the API.

** TODO Implement adaptive and uniform sampling for elliptic arcs
   :PROPERTIES:
   :CREATED:  2026-06-12 Fri 10:29
   :END:

* TODO Change the domains of Arc and LineSegment
  :PROPERTIES:
  :CREATED:  2026-06-12 Fri 10:12
  :END:

  Arc length parametrization is not possible for ellipses. It feels a bit bolted
  on to the arcs and lines too, since the internal representation just
  interpolates between 0 and 1, and we just pretend from the outside that they
  are length parametrized. It feels better to just parametrize Arc and
  LineSegment from 0 to 1, and just let the Spline do its thing.

* TODO Trimming Curves
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 18:13
  :END:

  - trim_left should remove the section of the curve from the start up to the
    provided parameter.
  - trim_right remove the section from the parameter to the end of the curve.
  - extract_interval should trim both the left and right sides of the given pair
    of parameters.

  It is yet unclear whether these functions should modify the curve in place, or
  return a modified copy. Needs more thought.

** TODO Knot Insertion
   :PROPERTIES:
   :CREATED:  2026-06-06 Sat 18:43
   :END:

   Inserting knots in a spline is required for splitting splines. The algo is
   described [[docview:~/zettelkasten/ntop-zettelkasten/data/e9/bbaa4f-ef2e-42ef-99ea-b489c591fbcf/The NURBS Book.pdf::152][here in the NURBS book]].

* TODO Projecting curves on to a plane
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 16:44
  :END:

  Once ellipses are figured out, this should be relatively trivial to implement.

  Since all curves are interpolations of points and vectors, this can be
  implemented more generally as an affine transformation of points.

* TODO Implement Polycurves
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 16:36
  :END:

  This will include the ability to join polycurves via the Euler walk.

* DONE loke (misc-features): Implement basic curve features
  CLOSED: [2026-06-06 Sat 16:32]
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 16:31
  :END:
  :LOGBOOK:
  - State "DONE"       from "NEXT"       [2026-06-06 Sat 16:32]
  - State "NEXT"       from "TODO"       [2026-06-06 Sat 16:32]
  :END:

  <2026-06-06 Sat 16:31> Implemented curvature query for all curve
  types. Merging this for now.
