#+title: Loke: Curve Library
#+author: Ranjeeth Mahankali

* TODO Trimming Curves
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 18:13
  :END:

  - trim_left should remove the section of the curve from the start up to the
    provided parameter.
  - trim_right remove the section from the parameter to the end of the curve.
  - extract_interval should trim both the left and right sides of the given pair
    of parameters.

  It is yet unclear whether these functions should modify the curve in place, or
  return a modified copy. Needs more thought.

** TODO Knot Insertion
   :PROPERTIES:
   :CREATED:  2026-06-06 Sat 18:43
   :END:

   Inserting knots in a spline is required for splitting splines. The algo is
   described [[docview:~/zettelkasten/ntop-zettelkasten/data/e9/bbaa4f-ef2e-42ef-99ea-b489c591fbcf/The NURBS Book.pdf::152][here in the NURBS book]].

* TODO Projecting curves on to a plane
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 16:44
  :END:

  Once ellipses are figured out, this should be relatively trivial to implement.

  Since all curves are interpolations of points and vectors, this can be
  implemented more generally as an affine transformation of points.

* TODO Implement Polycurves
  :PROPERTIES:
  :CREATED:  2026-06-06 Sat 16:36
  :END:

  This will include the ability to join polycurves via the Euler walk.
